// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6P-8cB4jKRQ_jVPL-EMaCOGhMyNSvTo',
    appId: '1:60114445530:web:0f0010f6e68320b939f1e3',
    messagingSenderId: '60114445530',
    projectId: 'nc-flutter-firebase-template',
    authDomain: 'nc-flutter-firebase-template.firebaseapp.com',
    storageBucket: 'nc-flutter-firebase-template.appspot.com',
    measurementId: 'G-E6K59S6L64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5x2pNZRKN2NYyE2xHohdW5XkhAm4p8MI',
    appId: '1:60114445530:android:a7e0dd24ba01734b39f1e3',
    messagingSenderId: '60114445530',
    projectId: 'nc-flutter-firebase-template',
    storageBucket: 'nc-flutter-firebase-template.appspot.com',
  );
}
