// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI2w3eEz30oWC-vbkrhzmF1DlxcnSatuY',
    appId: '1:989212230771:web:63f68f3e713e6d31ff1606',
    messagingSenderId: '989212230771',
    projectId: 'nc-flutter-firebase',
    authDomain: 'nc-flutter-firebase.firebaseapp.com',
    databaseURL: 'https://nc-flutter-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'nc-flutter-firebase.appspot.com',
    measurementId: 'G-3LSZD0KBLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCygPY2VYznTiEGnBo9LU_GMmv0lVtx6Hw',
    appId: '1:989212230771:android:c0798f12291f013cff1606',
    messagingSenderId: '989212230771',
    projectId: 'nc-flutter-firebase',
    databaseURL: 'https://nc-flutter-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'nc-flutter-firebase.appspot.com',
  );
}
